### ISSUE TITLE
关于SDL_TEXTEDITING_EXT事件的使用

### ISSUE THREAD

**Issue by LWshu0** [jinfeihan57/learn_SDL2#3]
在接收编辑事件时, 只会产生SDL_TEXTEDITING事件, 而不会产生SDL_TEXTEDITING_EXT事件, 希望可以写一个具体的例子演示如何使用

**Comment by jinfeihan57** [comment]
参考这个：https://github.com/jinfeihan57/learn_SDL2/blob/SDL_IME/hello_SDL2.cpp

如果github，回复太慢。可以在B站@我，提醒下
